baseURL       = "http://aidiyet.github.io/"
languageCode  = "tr-tr"
title         = "AÄ°DÄ°YET"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Anasayfa"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "HakkÄ±mÄ±zda"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "YayÄ±nlarÄ±mÄ±z"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "TED & Burslar"
    url     = "contact"
    weight  = 5
  [[menu.nav]]
    name    = "ğŸ“¸"
    url     = "https://instagram.com/tebankara/"
    weight  = 6

# Site Params
[params]
  logo = "images/anasayfa/anasayfa.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "AÄ°DÄ°YET BÃ¼lten | TEB Ankara Ã–ÄŸrencilerinin Kalemlerinden DoÄŸan Site"
  author = "Ozan Ali Altundal"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "Your ..."

  # Contact Form
  [params.contactForm]
    # placeholder_first_name        = "First Name"
    # placeholder_last_name         = "Last Name"
    # placeholder_email             = "Email"
    # placeholder_project_type      = "Project Type"
    # placeholder_about_the_project = "About the Project"
    button_1                  = "TED Anasayfa"
    button_2                  = "TED Burslar"

    # [[params.contactForm.projectType]]
    #   value = "gd"
    #   title  = "Graphics Design"
    # [[params.contactForm.projectType]]
    #   value = "wd"
    #   title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Aidiyet Projesi, 7'den 70'e herkesin ilgisini Ã§ekecek iÃ§eriklerle sizlere ulaÅŸmayÄ± amaÃ§lar."
    tagline               = "TEB Ankara | AÄ°DÄ°YET ğŸ“°"
    primary_button        = "YayÄ±nlarÄ±mÄ±z"
    primary_button_url    = "portfolio"
    secondary_button      = "Ä°Ã§eriklerimiz"
    secondary_button_url  = "blog"

  [params.portfolio]
    enable    = true
    title     = "EN SON Ã‡IKAN BÃœLTENLERÄ°MÄ°Z"
    subtitle  = "EÄŸlendirici ve bilgilendirici iÃ§eriklerimiz sizlerin okumasÄ±nÄ± bekliyor!"

  [params.call_to_action]
    enable              = false
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LETâ€™S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Ä°letiÅŸim Bilgileri"
      email   = "dergi.aidiyet@gmail.com"
      phone   = ""
      address = ""

      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Site HaritasÄ±"
        [[params.footer.sitemap.link]]
          name = "HakkÄ±mÄ±zda"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "YayÄ±nlarÄ±mÄ±z"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "TED & Burslar"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "ğŸ“¸ Instagram - TEB Ankara"
          url  = "https://instagram.com/tebankara/"
        [[params.footer.social.link]]
          name = "ğŸ“¸ Instagram - Aidiyet"
          url  = "#"
        [[params.footer.social.link]]
          name = "ğŸ”— LinkedIn"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "Aidiyet Nedirâ”"
        description = "Vizyonumuz; Aidiyet ekibi olarak TED ile yollarÄ± kesiÅŸmiÅŸ her yaÅŸtan insana ulaÅŸmak ve kendimizi tanÄ±tmak, bilgilerimizi paylaÅŸmak..."